# Generated by Django 4.1.2 on 2022-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
